### ISSUE TITLE
Переименуйте репозиторию

### ISSUE THREAD

**Issue by oleg-tgn** [sherik1998/program#1]
Может быть много различных лабораторных.
Нужно назвать репозиторий более понятно по названию предмета.

Лучше так, `OAiP_labs_Eloev`. Тогда, если мне необходимо будет скачать репозиторий себе для тестирования программ и их будет несколько, я сразу буду соотносить где чья

**Comment by sherik1998** [comment]
А как его переименовать?

**Comment by oleg-tgn** [comment]
Зайдите в `Settings `и напишите там `OAiP_labs_Eloev`

**Comment by sherik1998** [comment]
Спасибо все получилось

**Comment by oleg-tgn** [comment]
Отлично!
