### ISSUE TITLE
Код (2 лаба)

### ISSUE THREAD

**Issue by oleg-tgn** [sherik1998/program#10]
1) Не чересчур ли громоздкое имя `OAiP_labs_Eloev lab №2 var №2` ?

2) А сам проект не переделывали. Так и остался `Проект 1`

3) Смотрите комментарии в коммитах

https://github.com/sherik1998/OAiP_labs_Eloev/commit/14990b2db8ea5874a24265b46051394a0d1cdbe2

https://github.com/sherik1998/OAiP_labs_Eloev/commit/4539bc08b6cb13a68f51a609a3931e8d7da2c85c

4) неверное именования функций. см рекомендации в другом коммите и в вики

5) зачем передавать параметр void? если можно просто не передавать параметры

6) почему массив называется array что просто переводится как "массив"
может лучше назвать его values или data
подумайте какое имя подойдет

7) если для проверки ввода длины массива и так задали отдельную функцию. зачем проверять тут?

8) почему в сообщении 100 числом, а не константой?
а если константа поменяется на 1000
так и будете выводить сообщение с числом 100?

9) объявляйте переменную сразу внутри цикла for, так короче

10) тут можно использовать короткое имя переменной i
для счетчиков цикла допустимо использовать короткие имена

11) две функции делают одно и то же
может написать одну функцию для проверки и просто подменять сообщения в ней?

12) не нужно называть функцию - "функция"

- название должно показывать что эта функция делает
- должно начинаться с глагола
- не должно быть функций с именами функция1, функция2, функция3
- именования должны вестись без знаков подчеркивания, а каждое слово слово следует -
 начинать с большой буквы
- первое слово должно быть с маленькой буквы
- первое слово должно быть глаголом
- читайте вики раздел "Именования"

**Comment by sherik1998** [comment]
Я все исправил вроде
и залил

**Comment by Romania322** [comment]
закрыть
