### ISSUE TITLE
Индивидуалка

### ISSUE THREAD

**Issue by oleg-tgn** [sherik1998/program#20]
В целом просматривая код, результат хороший. Разбит на функции, все достаточно логично. 

Но как и всегда дьявол в мелочах

1) `char* p_FIO = (char*)(malloc(sizeof(char) * 254));`
- почему именование переменно не в CamelCase стиле?
- какой смысл выделять память динамически для этой переменной и для других строк, если количество этой памяти не меняется в дальнейшем, ведь проще было бы написать `char p_FIO[254];`
- 254 - выносим в define

2) Зачем везде эта приставка `p_`?

3) `clients* ClientBase()` - имена функций, почему с большой буквы?

4) Зачем в if и в while проверять одно и тоже? И создавать тем самым лишние воженности

```
if (!feof(clntFile))
	{
		int inc = 0;
		while (!feof(clntFile))
		{
```

5) Проще намного было бы использовать fscanf("%s,%s,%s") с разделителем в виде запятой, чем создавать вот эти громоздкие и плохо читаемые конструкции

```
CBase[inc].p_FIO = strtok_s(buff, ",", &p_tokken);
CBase[inc].p_Number = strtok_s(NULL, ", ", &p_tokken);
CBase[inc].p_fDate = strtok_s(NULL, ", ", &p_tokken);
CBase[inc].p_lDate = strtok_s(NULL, ",", &p_tokken);
CBase[inc].debt = atof(strtok_s(NULL, ",", &p_tokken));
CBase[inc].credit = atof(strtok_s(NULL, ",", &p_tokken));
```

6) Вот это прям кошмар какой-то

Давайте установим следующее правило. Не более 40-50 строк на одну функцию. Не более 3х вложений кода один в другой.

```
void searchFunc(clients* cBase, service* sBase, bill* bBase, char** key)
{
	FILE* oFile = fopen(p_oFile, "w+");
	fputs("Ôàìèëèÿ: ---   Íîìåð òåëåôîíà ---- Äàòà çàêëþ÷åíèÿ äîãîâîðà ----  Óñëóãè -----\n", oFile);
	for (int a = 0; a < kSize; a++)
	{
		for (int b = 0; b < cSize; b++)
		{
			if (!strcmp(cBase[b].p_FIO, key[a]) && is_SecQuartal(cBase[b].p_fDate))
			{
				fputs(key[a], oFile);
				fputs(" ", oFile);
				fputs(cBase[b].p_Number, oFile);
				fputs(" ", oFile);
				fputs(cBase[b].p_fDate, oFile);
				fputs(" :", oFile);
				for (int c = 0; c < bSize; c++)
				{
					if (!strcmp(cBase[b].p_Number, bBase[c].p_Number))
					{
						for (int d = 0; d < sSize; d++)
						{
							if (bBase[c].code == sBase[d].code)
							{
```

7) Тут лучше для читаемости кода объявить все функции в начале перед main. Потом вызвать main и далее уже остальные функции

**Comment by sherik1998** [comment]
я просто спешил думал времени не хватит

**Comment by sherik1998** [comment]
все исправлю

**Comment by sherik1998** [comment]
Исправил 2, 3, 4, 6 и 7 пункты
1 пункт при переделки под простое выделение памяти в и тоги вы даёт ошибку вовремя считывания с файла, смог сделать только #define 
5 пункт fscanf считывает да пробела, а так как по условию задачи нужно вводить имя фамилию и отчество через пробел, он не считывает и завершается с ошибкой, по этому я считываю через strtok
