### ISSUE TITLE
Обработка некорректных данных

### ISSUE THREAD

**Issue by oleg-tgn** [sherik1998/program#5]
Как будет вести себя программа, если вместо числа я буду вводить буквы, всегда ли она корректно отработает и выдаст сообщение об ошибке?

**Comment by sherik1998** [comment]
![image](https://user-images.githubusercontent.com/31658896/31047762-1aa35904-a619-11e7-97a7-b8d5ed99e52b.png)

**Comment by oleg-tgn** [comment]
Теперь хорошо. Давайте сделаем, чтобы ввод нового числа был с новой строки, иначе чуть плохо читается, когда и ошибка и ввод нового числа там же.

Еще давайте выведем более понятное сообщение о результатах. Сделайте на свое усмотрение.
Можно так
```
90 узлов = 166.5 км/ч
90 узлов = 46.3 м/с
```

**Comment by sherik1998** [comment]
А можно сделать так:
90 узлов = 166,5 км/ч = 46 м/с

**Comment by sherik1998** [comment]
вот так пойдёт
![image](https://user-images.githubusercontent.com/31658896/31092765-19a2832c-a7b8-11e7-9333-9ca437cedfb2.png)

**Comment by sherik1998** [comment]
все цифровые значения я заменил на константы 
![image](https://user-images.githubusercontent.com/31658896/31093011-ff24fa60-a7b8-11e7-9685-fb28353cd5f2.png)

**Comment by sherik1998** [comment]
![image](https://user-images.githubusercontent.com/31658896/31093030-113b6dc4-a7b9-11e7-9c59-4aee113ce32d.png)

**Comment by oleg-tgn** [comment]
Да, хорошо. 

Только давайте без такого количества восклицательных знаков, а то у пользователя вашей программы будет приступ паники:)

Займитесь именование переменных и констант. Они должны носить осмысленные имена.

У меня есть про это в вики. Если хотите чуть подробнее тут https://learn.javascript.ru/variable-names (То что учебник JS не обращайте внимания, актуально для многих языков, в том числе для Си)

**Comment by sherik1998** [comment]
вот так пойдет?
![image](https://user-images.githubusercontent.com/31658896/31132530-ada5e4d0-a865-11e7-8d3f-0fa1c1ecbd9c.png)
![image](https://user-images.githubusercontent.com/31658896/31132548-b92089dc-a865-11e7-9614-650168af6a2d.png)

**Comment by sherik1998** [comment]
Если не видно то я уже залил

**Comment by sherik1998** [comment]
отчет уже можно начинать делать?

**Comment by oleg-tgn** [comment]
Конечно
