### ISSUE TITLE
Рекомендации

### ISSUE THREAD

**Issue by oleg-tgn** [sherik1998/program#6]
https://github.com/oleg-tgn/for-students/wiki

**Comment by sherik1998** [comment]
Как исправить в visual studio 2017 сохранить в юникоде?

**Comment by oleg-tgn** [comment]
Просто вбил Ваш вопрос в Google:)

https://msdn.microsoft.com/ru-ru/library/dxfdkfke.aspx

**Comment by sherik1998** [comment]
Я сам искал но мне только почему то 2015 вечно выкидывала
спасибо все получилось

**Comment by oleg-tgn** [comment]
Отлично!
