### ISSUE TITLE
Замечания по коду

### ISSUE THREAD

**Issue by oleg-tgn** [sherik1998/program#7]
1) [Название проектов](https://github.com/oleg-tgn/for-students/wiki/%D0%98%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)
lab[номер лабораторно]-[номер варианта]

2) Файл тоже должен носить корректное имя по смыслу, можно называть так же как лабораторную
`Source.cpp`

3) Что-то все слишком прилипло
добавьте отступы
например так

```
/* 
    Елоев Георгий Александрович
    КТБО 1-8
    Лабораторная № 2
    Вариант №2
    Задание: Написать программу, которая вычисляет среднее арифметическое элементов 
массива без учета минимального и максимального элементов массива. Массив и
его длина вводятся пользователем.
*/
```

4) Почему огромный разрыв?

```
#define MIN_LENGTH 3



int main()
```

5) Не хватает проверки при вводе данных в массив. Плюс вынести проверку на корректность ввода в [отдельную функцию. ](https://github.com/oleg-tgn/for-students/wiki/%D0%9C%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D1%8B)

6) Не нужно использовать min_max переменную, сделайте отдельную переменную для min и для max

7) 
```
for (counter = 0; counter < (length - 1); counter++)
	{
		if (array[counter] > array[counter + 1])
		{
			min_and_max = array[counter + 1];
			array[counter + 1] = array[counter];
			array[counter] = min_and_max;
		}
	}
	for (counter = 0; counter < (length - 2); counter++)
	{
		if (array[counter] < array[counter + 1])
		{
			min_and_max = array[counter + 1];
			array[counter + 1] = array[counter];
			array[counter] = min_and_max;
		}
	}
```

Кажется вот этот запутанный алгоритм я уже видел, и мы как-то его уже исправляли...
Это было с Вами?

**Comment by sherik1998** [comment]
на счет алгоритма мы его исправили
но при вводе массива 5;4;3;2;1
то код который мы с вами переделали то получается что мак 5 и мин 1 стоят на первом и последнем месте ,как видно, то тогда когда мы делали так как мы собирались делать тогда то 5 и 1 менялись местами , так как по вашему алгоритму максимальный элемент идёт на последнее место, то получается следующие  1;4;3;2;5 , и потом он меняет местами и получается 1;4;3;5;2, так как по нашему алгоритму мы запоминали только номера в массиве минимального и максимального значения

**Comment by sherik1998** [comment]
и я нашел вход из этой ситуации можно просто обнулить максимальны и минимальный массив

**Comment by sherik1998** [comment]
я сегодня все исправлю и заново закину в гит

**Comment by oleg-tgn** [comment]
ок)

**Comment by sherik1998** [comment]
а проверка ввода данных в массив есть
![image](https://user-images.githubusercontent.com/31658896/32181193-d4f35e56-bda4-11e7-8722-ee070da57c5c.png)

**Comment by sherik1998** [comment]
насчет 6 пункта теперь надобность в min_max или buf полностью отпадёт

**Comment by sherik1998** [comment]
1 и 2 пункт исправил 
![image](https://user-images.githubusercontent.com/31658896/32181527-9d5f535e-bda5-11e7-9d7d-afce64eef737.png)
![image](https://user-images.githubusercontent.com/31658896/32181549-a6d7c916-bda5-11e7-9011-dc8d64a4eeff.png)

**Comment by sherik1998** [comment]
насчет 3 и 4 пункта не совсем понял что исправить?

**Comment by sherik1998** [comment]
В 3 и 4 вот так исправить
![image](https://user-images.githubusercontent.com/31658896/32182594-22ee11c0-bda8-11e7-9a35-a2058e4a95be.png)

**Comment by oleg-tgn** [comment]
3 - просто не писать такие большие комментарии вплотную
4 - много пропусков строк в коде
Это просто по стилю кода

**Comment by sherik1998** [comment]
а почему у меня за код 1 балл?

**Comment by sherik1998** [comment]
эта строчка с if нужна мне для того чтобы пользователю выводилась надпись об ошибке если он вел число больше 100 или меньше 3 , а если в функцию это все закинуть то приходилось два раза нажимать на энтер нажимать чтобы программа продолжала работать
![image](https://user-images.githubusercontent.com/31658896/32292964-bbb12c3e-bf52-11e7-9d07-80d2e2da3634.png)

**Comment by oleg-tgn** [comment]
Думаю, код достоин уже 2 баллов из 3. Сейчас напишу новые
