### ISSUE TITLE
Замечания по отчету

### ISSUE THREAD

**Issue by oleg-tgn** [sherik1998/program#8]
1) Если открыть в OpenOffice видим вот такую картинку. Используйте неразрывные пробелы
![2017-10-30 12 49 31](https://user-images.githubusercontent.com/16413346/32164524-dc027a58-bd70-11e7-90b8-b2e8d9013c8d.png)

2) Что за пункт отчета такой "Объявление массива"? Зачем он нужен?

3) Если `1.Объявление массива`, `2.Создание алгоритма` это отдельные пункты, тогда они должны начинаться с новой строки, быть оформлены как заголовки

4) Блок-схема - это описание алгоритма работы программы, а не вставка кусков кода в квадратики и кружочки. Не годится. 
https://pro-prof.com/archives/1462
https://ru.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%BA-%D1%81%D1%85%D0%B5%D0%BC%D0%B0
https://sites.google.com/site/anisimovkhv/learning/pris/lecture/tema8/tema8_2

5) [Заголовки должны быть оформлены](https://github.com/oleg-tgn/for-students/wiki/%D0%9E%D1%82%D1%87%D0%B5%D1%82)

6) Разделы должны начинаться с новой строки

7) Если указали рисунки, тогда в тексте нужно писать. Такое-то дейставие показано на рисунке 1. И далее уже рисунок

8) Почему все рисунки так близко друг к другу? 

9) Межстрочный интервал не соблюдается

10) Отступы в начале каждого абзаца не соблюдаются

11) В любый научных работах, отчетах, рефератах, курсовых и тому подобное не должно использоваться личного местоимения Я, моя, моя и прочее...

Результат по отчету пока 0 баллов из 2

**Comment by sherik1998** [comment]
я переделаю

**Comment by sherik1998** [comment]
я сейчас закину отчет вместе с лабой но только в отчете нет пока блок схемы она в процессе

**Comment by sherik1998** [comment]
я залил отчет и лабу , в отчете пока нет блок схемы , можете из просмотреть?

**Comment by sherik1998** [comment]
их*

**Comment by oleg-tgn** [comment]
И код и отчет? Хорошо, я посмотрю, но возможно, не сегодня

**Comment by sherik1998** [comment]
В общем мне стало скучно и я сделал блок-схему, вставил её в отчет и залил в гид

**Comment by oleg-tgn** [comment]
Хорошо, сегодня буду смотреть

**Comment by sherik1998** [comment]
а что в отчёте ещё неправильно

**Comment by oleg-tgn** [comment]
Сейчас посмотрю еще раз. Напишу отдельный issue
