### ISSUE TITLE
Отчет (2 лаба)

### ISSUE THREAD

**Issue by oleg-tgn** [sherik1998/program#9]
у меня не отрывается в open office по каким-то причинам. сохраните, пожалуйста, отчет дополнительно в pdf

**Comment by oleg-tgn** [comment]
1) [Структура отчета пункт 6](https://github.com/oleg-tgn/for-students/wiki/%D0%9E%D1%82%D1%87%D0%B5%D1%82)

2) Цели работы. [Методическое пособие 5044 ](https://drive.google.com/drive/u/1/folders/0B6vk8QrSYLYbU21OTU1KR18ydmc)
Тут есть цель работы. И она отличается от Вашей

3) Напишите вариант работы на титульном под темой

4) Алгоритм у меня поехал. Приложите pdf

5) Сделайте в блок-схеме белый фон

6) Разбейте блок-схему на 2 страницы. Сейчас явно все очень мелко и нечитаемо

7) Программный код - почему-то не заголовок

8) `2.Программный код.` - убираем цифру и точку в конце
Аналогично для вашего раздела "тестирование"

9) "Вывод" и другие разделы начинам с новой страницы

**Comment by sherik1998** [comment]
4 пункт я не знаю как pdf сделать
